"""Plot the CART4-34 screening values reported in the 2024 CURF poster.

Source: assets/pdf/curf_poster.pdf, Figure VI and its control caption.
The CSV records reported percentages, not replicate-level measurements.
Donor counts, replicate counts, and uncertainty were not reported; no
error bars, statistical tests, or assumed sample sizes are generated.

Regenerate from any directory with a Python environment containing matplotlib:
    python path/to/plot_screening.py

Outputs are vector SVG (website/card) and PDF (inspection/export).
The 6.75 x 3.80 inch canvas is 16:9 and uses the vendored figure style.
"""

import csv
from pathlib import Path
import sys

import matplotlib.pyplot as plt

# Keep generated bytecode out of the website's public assets directory.
sys.dont_write_bytecode = True
from orx_figstyle import MUTED, PALETTE, WIDE, figure, save, use_style


HERE = Path(__file__).resolve().parent
LABELS = ["Control", "RetroNectin\nonly", "P407\nonly", "RetroNectin\n+ P407"]


def main():
    with (HERE / "screening-data.csv").open(newline="") as handle:
        rows = list(csv.DictReader(handle))
    values = [float(row["egfr_positive_percent"]) for row in rows]
    if len(rows) != len(LABELS):
        raise ValueError("Expected four source-reported screening conditions")

    use_style()
    plt.rcParams.update({
        "font.size": 12,
        "axes.labelsize": 13,
        "xtick.labelsize": 12,
        "ytick.labelsize": 11,
        "svg.hashsalt": "cart434-screening-2024",
    })
    fig, ax = figure(width=WIDE, ratio=9 / 16)
    fig.set_facecolor("white")
    ax.set_facecolor("white")
    bars = ax.bar(
        range(len(rows)), values, width=0.62,
        color=[MUTED, MUTED, MUTED, PALETTE["blue"]],
        edgecolor="#46515B", linewidth=0.5,
    )
    ax.bar_label(bars, fmt="%.1f%%", padding=6, fontsize=15, fontweight="bold")
    ax.set_xticks(range(len(rows)), LABELS)
    ax.set_ylabel("EGFR-positive cells (%)", labelpad=9)
    ax.set_ylim(0, 42)
    ax.set_yticks([0, 10, 20, 30, 40])
    ax.tick_params(axis="x", length=0, pad=8)
    ax.tick_params(axis="y", length=0, pad=6)
    ax.spines["left"].set_visible(False)
    ax.spines["bottom"].set_color("#7F7F7F")
    ax.grid(axis="y", color="#E1E5E8", linewidth=0.6)
    ax.grid(axis="x", visible=False)
    ax.margins(x=0.08)
    save(fig, str(HERE / "transduction-screening"))


if __name__ == "__main__":
    main()
